apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: soap
  created: ""
  updated: ""
spec:
  nodes:
  - general:
      hostname: provider
    hardware:
      drives:
      - image: bennu.qc2
      os_type: linux
    network:
      interfaces:
      - address: 172.16.1.2
        gateway: 172.16.1.1
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      hostname: ignition
    hardware:
      drives:
      - image: ignitionhmi.qc2
      memory: 4096
      os_type: linux
      vcpus: 2
    network:
      interfaces:
      - address: 10.117.4.70
        gateway: 10.117.4.1
        mask: 24
        name: exp
        proto: static
        type: ethernet
        vlan: EXP
      - address: 172.16.1.3
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      hostname: rtu-1
    hardware:
      drives:
      - image: bennu.qc2
      memory: 512
      os_type: linux
      vcpus: 1
    network:
      interfaces:
      - address: 10.117.4.101
        mask: 24
        name: exp
        proto: static
        type: ethernet
        vlan: EXP
      - address: 172.16.1.4
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      hostname: rtu-2
    hardware:
      drives:
      - image: bennu.qc2
      memory: 512
      os_type: linux
      vcpus: 1
    network:
      interfaces:
      - address: 10.117.4.102
        mask: 24
        name: exp
        proto: static
        type: ethernet
        vlan: EXP
      - address: 172.16.1.5
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      hostname: rtu-3
    hardware:
      drives:
      - image: bennu.qc2
      memory: 512
      os_type: linux
      vcpus: 1
    network:
      interfaces:
      - address: 10.117.4.103
        mask: 24
        name: exp
        proto: static
        type: ethernet
        vlan: EXP
      - address: 172.16.1.6
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      hostname: rtu-4
    hardware:
      drives:
      - image: bennu.qc2
      memory: 512
      os_type: linux
      vcpus: 1
    network:
      interfaces:
      - address: 10.117.4.104
        mask: 24
        name: exp
        proto: static
        type: ethernet
        vlan: EXP
      - address: 172.16.1.7
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      hostname: controlthings_elk
    hardware:
      drives:
      - image: controlthingsplatform.qc2
      memory: 4096
      os_type: linux
      vcpus: 1
    network:
      interfaces:
      - address: 10.117.4.1
        mask: 24
        name: exp
        proto: static
        type: ethernet
        vlan: EXP
      - address: 172.16.1.8
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
      - address: 0.0.0.0
        mask: 0
        name: mirror
        proto: static
        type: ethernet
        vlan: MIRROR
    type: VirtualMachine
