apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: waterway 
  created: ""
  updated: ""
spec:
  nodes:
  - general:
      description: SCEPTRE Simulink fuel provider
      hostname: simulink-provider
    hardware:
      drives:
      - image: bennu.qc2
      memory: 8192
      os_type: linux
      vcpus: 4
    network:
      interfaces:
      - address: 172.16.1.2
        gateway: 172.16.1.1
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: OPC server
      hostname: opc
    hardware:
      drives:
      - image: opc.qc2
        inject_partition: 2
      memory: 4096
      os_type: windows
    network:
      interfaces:
      - address: 10.1.2.50
        gateway: 10.1.2.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: SCADA
      - address: 172.16.2.50
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: Historian server
      hostname: historian
    hardware:
      drives:
      - image: historian.qc2
        inject_partition: 2
      memory: 2048
      os_type: windows
    network:
      interfaces:
      - address: 10.1.2.60
        gateway: 10.1.2.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: SCADA
      - address: 172.16.2.60
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: Server
  - general:
      description: Human machine interface
      hostname: hmi
    hardware:
      drives:
      - image: hmi_win7.qc2
      memory: 2048
      os_type: windows
    network:
      interfaces:
      - address: 10.1.2.70
        gateway: 10.1.2.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: SCADA
      - address: 172.16.2.70
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: SCADA server
      hostname: scada-server
    hardware:
      drives:
      - image: scada.qc2
        inject_partition: 2
      memory: 2048
      os_type: windows
    network:
      interfaces:
      - address: 10.1.2.71
        gateway: 10.1.2.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: SCADA
      - address: 172.16.2.71
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: Engineering workstation
      hostname: engineer-workstation
    hardware:
      drives:
      - image: engineer_workstation.qc2
      memory: 2048
      os_type: windows
    network:
      interfaces:
      - address: 10.1.2.72
        gateway: 10.1.2.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: SCADA
      - address: 172.16.2.72
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: SCEPTRE RTU
      hostname: rtu-1
    hardware:
      drives:
      - image: bennu.qc2
      os_type: linux
      vcpus: 2
    network:
      interfaces:
      - address: 10.1.1.101
        gateway: 10.1.1.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: ICS
      - address: 172.16.1.101
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: SCEPTRE RTU
      hostname: rtu-2
    hardware:
      drives:
      - image: bennu.qc2
      os_type: linux
      vcpus: 2
    network:
      interfaces:
      - address: 10.1.1.102
        gateway: 10.1.1.1
        mask: 24
        name: IF0
        proto: static
        type: ethernet
        vlan: ICS
      - address: 172.16.1.102
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
    type: VirtualMachine
  - general:
      description: Router
      hostname: router
    hardware:
      drives:
      - image: minirouter.qc2
      os_type: minirouter
    network:
      interfaces:
      - address: 10.1.2.1
        mask: 24
        name: IF0
        proto: ospf
        type: ethernet
        vlan: SCADA
      - address: 10.1.1.1
        mask: 24
        name: IF1
        proto: ospf
        type: ethernet
        vlan: ICS
      - address: 172.16.1.1
        mask: 16
        name: mgmt
        proto: static
        type: ethernet
        vlan: MGMT
      ospf:
        areas:
        - area_id: 0
          area_networks:
          - network: 10.1.2.0/24
          - network: 10.1.1.0/24
        router_id: 0.0.0.1
    type: Router
